# Vectors and matrices with numpy

Hola mi joven Padawan,

Cuando te enseñaron Python, te hablaron de las listas.

Pero las listas no son muy cómodas para representar vectores. 

Igual que las listas de listas no lo son para representar matrices.

`Numpy` soluciona esto.

<br>

Esta sesión es más un recopilatorio.

Una referencia para arrancar con lo básico.

Todo es muy intuitivo, así que vamos a ir rápido.

_¡Vamos!_

## You will find...

1. [Initializing vectors](#initializing-vectors)
2. [Initializing matrices](#initializing-matrices)
3. [Accessing info about the vector or matrix](#accessing-info)
4. [Addition, matrix multiplication and dot product](#addition-multiplication-dot)
5. [Mathematical functions in `numpy`](#mathematical-functions-numpy)
6. [Boolean operators](#boolean-operators)
7. [Aggregation functions](#aggregation-functions)

In [1]:
import numpy as np

Fix the randomness seed for replicability:

In [2]:
np.random.seed(734)

<a id="initializing-vectors"></a>
## Initializing vectors

Let's define the same dimension for all of them

In [3]:
dim = 5

1) Array from given values (dimension is inferred)

In [4]:
v = np.array([1,3.4,-6,.025,73])

2) Empty array with given dimension (locates space!)

In [5]:
e = np.empty(dim)

3) Array filled with: `a` ones, `b` zeros, `f` custom value

In [6]:
a = np.ones(dim)

In [7]:
b = np.zeros(dim)

In [8]:
f = np.full(dim, 3.17)

4) Copy an array

If you use `c=v` instead, you are not creating a new copy!

In [9]:
c = np.copy(v)

5) Array of random values (between 0 and 1)

In [10]:
r = np.random.random(dim)

<a id="initializing-matrices"></a>
## Initializing matrices

Matrices are arrays with two-element `shape=(num_rows, num_cols)`.

The previous methods can also be used.

Just replace the integer valued dim with a tuple.

In [11]:
mat = np.array([[0.70, 0.62, 5.96, 0.11, 0.20],
                [0.36, 4.35, 0.72, -22.89, 0.85],
                [-7.75, -3.18, 3.76, 0.91, 0.03],
                [0.21, -0.97, 0.12, 0.78, 13.01],
                [4.94, 1.60, 0.70, 14.26, 0.50]])

In [12]:
rmat = np.random.random((dim, dim))

In [13]:
onesmat = np.ones((3*dim, dim))

<a id="accessing-info"></a>
## Accessing info about the vector or matrix

We can obtain the dimension with the `shape` attribute:

In [14]:
v.shape, e.shape, a.shape, b.shape, f.shape, c.shape, r.shape

((5,), (5,), (5,), (5,), (5,), (5,), (5,))

For matrices,

In [15]:
mat.shape, rmat.shape, onesmat.shape

((5, 5), (5, 5), (15, 5))

The values of the arrays are accessed by indexing:

In [16]:
v[1], f[3], c[1], r[1], mat[1,3], onesmat[12,2]

(3.4, 3.17, 3.4, 0.31927137812331163, -22.89, 1.0)

You can access several indices too.

Returns vectors with those elements

In [17]:
v[3:], v[2:4], v[[1, 3]]

(array([2.5e-02, 7.3e+01]), array([-6.   ,  0.025]), array([3.4  , 0.025]))

or the corresponding sub-matrices

In [18]:
mat[3:, 1:]

array([[-0.97,  0.12,  0.78, 13.01],
       [ 1.6 ,  0.7 , 14.26,  0.5 ]])

To access the upper-left 3x3 corner:

In [19]:
mat[:3, :3]

array([[ 0.7 ,  0.62,  5.96],
       [ 0.36,  4.35,  0.72],
       [-7.75, -3.18,  3.76]])

The elements of an array can be iterated.

But you will RARELY NEED it.

Almost all you need is already implemented with a much more efficient function.

<a id="addition-multiplication-dot"></a>
## Addition, matrix multiplication and dot product

Arrays that have the same shape can be added and substracted.

In [20]:
v+r

array([ 1.79048548,  3.71927138, -5.63125973,  0.40518157, 73.79607726])

In [21]:
v-r

array([ 0.20951452,  3.08072862, -6.36874027, -0.35518157, 72.20392274])

In [22]:
mat+rmat

array([[  1.58415271,   0.82733455,   6.29655989,   0.20884242,
          1.08051455],
       [  0.88898926,   4.89929672,   0.72514543, -22.59088473,
          1.84500774],
       [ -7.38426858,  -2.38760561,   4.67160119,   1.05838572,
          0.91579577],
       [  0.22332179,  -0.13600152,   0.874788  ,   1.6569578 ,
         13.63505787],
       [  5.79972802,   2.27929048,   1.68364833,  15.16910999,
          0.54224241]])

They can also be multiplied by a scalar (an int, float or complex)

In [23]:
4*v+.333*r

array([ 4.26323166e+00,  1.37063174e+01, -2.38772095e+01,  2.26600464e-01,
        2.92265094e+02])

In [24]:
(1+2j) * mat

array([[  0.7  +1.4j ,   0.62 +1.24j,   5.96+11.92j,   0.11 +0.22j,
          0.2  +0.4j ],
       [  0.36 +0.72j,   4.35 +8.7j ,   0.72 +1.44j, -22.89-45.78j,
          0.85 +1.7j ],
       [ -7.75-15.5j ,  -3.18 -6.36j,   3.76 +7.52j,   0.91 +1.82j,
          0.03 +0.06j],
       [  0.21 +0.42j,  -0.97 -1.94j,   0.12 +0.24j,   0.78 +1.56j,
         13.01+26.02j],
       [  4.94 +9.88j,   1.6  +3.2j ,   0.7  +1.4j ,  14.26+28.52j,
          0.5  +1.j  ]])

Other Python operators are also defined on arrays.

They usually act elementwise:

In [25]:
v**2

array([1.000e+00, 1.156e+01, 3.600e+01, 6.250e-04, 5.329e+03])

In [26]:
v > r

array([ True,  True, False, False,  True])

In [27]:
mat < 2

array([[ True,  True, False,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True, False],
       [False,  True,  True, False,  True]])

In [28]:
v*r

array([ 7.90485479e-01,  1.08552269e+00, -2.21244164e+00,  9.50453936e-03,
        5.81136399e+01])

In [29]:
mat*rmat

array([[ 6.18906899e-01,  1.28547420e-01,  2.00589695e+00,
         1.08726657e-02,  1.76102910e-01],
       [ 1.90436133e-01,  2.38944072e+00,  3.70471121e-03,
        -6.84674861e+00,  8.45756578e-01],
       [-2.83441852e+00, -2.51981415e+00,  3.42762046e+00,
         1.35031005e-01,  2.65738730e-02],
       [ 2.79757597e-03, -8.08978530e-01,  9.05745604e-02,
         6.84027084e-01,  8.13200288e+00],
       [ 4.24705644e+00,  1.08686477e+00,  6.88553829e-01,
         1.29639084e+01,  2.11212034e-02]])

`@` can be used to perform matrix multiplication.

It can also be implemented with `np.dot` function.

In [30]:
mat @ v

array([-18.34925,  72.30775, -38.90925, 945.9415 ,  43.0365 ])

In [31]:
np.dot(mat, v)

array([-18.34925,  72.30775, -38.90925, 945.9415 ,  43.0365 ])

In [32]:
mat.dot(v)

array([-18.34925,  72.30775, -38.90925, 945.9415 ,  43.0365 ])

`@` and `np.dot` also implement the inner product between vectors:

In [33]:
v @ r

57.78671096606

In [34]:
np.dot(v, r)

57.78671096606

In [35]:
v.dot(r)

57.78671096606

When working with complex vectors it is also common to take the complex conjugate of the first vector to perform the dot product.

This is implemented in the `np.vdot` function (it should only be used for vectors):

In [36]:
v1 = np.array([5j, -1+3j, -4j])
v2 = np.array([0.4, -1+0.5j, -1j])

In [37]:
np.dot(v1, v2)

(-4.5-1.5j)

In [38]:
np.vdot(v1, v2)

(6.5+0.5j)

In [39]:
np.vdot(v2, v1)

(6.5-0.5j)

Matrices can be transposed with `np.transpose`:

In [40]:
np.transpose(mat)

array([[  0.7 ,   0.36,  -7.75,   0.21,   4.94],
       [  0.62,   4.35,  -3.18,  -0.97,   1.6 ],
       [  5.96,   0.72,   3.76,   0.12,   0.7 ],
       [  0.11, -22.89,   0.91,   0.78,  14.26],
       [  0.2 ,   0.85,   0.03,  13.01,   0.5 ]])

In [41]:
mat.transpose()

array([[  0.7 ,   0.36,  -7.75,   0.21,   4.94],
       [  0.62,   4.35,  -3.18,  -0.97,   1.6 ],
       [  5.96,   0.72,   3.76,   0.12,   0.7 ],
       [  0.11, -22.89,   0.91,   0.78,  14.26],
       [  0.2 ,   0.85,   0.03,  13.01,   0.5 ]])

<a id="mathematical-functions-numpy"></a>
## Mathematical functions in `numpy`

These functions act elementwise.

The exponential:

In [42]:
np.exp(v)

array([2.71828183e+00, 2.99641000e+01, 2.47875218e-03, 1.02531512e+00,
       5.05239363e+31])

Trigonometric functions:

In [43]:
np.sin(v)

array([ 0.84147098, -0.2555411 ,  0.2794155 ,  0.0249974 , -0.67677196])

In [44]:
np.cos(v)

array([ 0.54030231, -0.96679819,  0.96017029,  0.99968752, -0.73619272])

In [45]:
np.tan(v)

array([1.55740772, 0.2643169 , 0.29100619, 0.02500521, 0.9192864 ])

In [46]:
np.sin(v)**2+np.cos(v)**2

array([1., 1., 1., 1., 1.])

Absolute value:

In [47]:
np.abs(v)

array([1.0e+00, 3.4e+00, 6.0e+00, 2.5e-02, 7.3e+01])

Custom functions:

In [48]:
def my_function(x):
    return 4 * np.exp(x**2 / 9)

In [49]:
my_function(v)

array([4.47007627e+000, 1.44506415e+001, 2.18392600e+002, 4.00027779e+000,
       5.65780820e+257])

<a id="boolean-operators"></a>
## Boolean operators

`>`,`<`,`and`, and `or` act elementwise.

To build boolean clauses that return `True` or `False` one can use the operators `np.any` and `np.all`.

In [50]:
v < r

array([False, False,  True,  True, False])

In [51]:
np.any(v < r)

True

In [52]:
np.all(v < r)

False

This is particullarly useful to check if two vectors have similar entries.

For instance, to check if all the entries are within `0.01` distance:

In [53]:
np.all(np.abs(v-r) < 0.01)

False

<a id="aggregation-functions"></a>
## Aggregation functions

Aggregation functions take an array and return a single value. For instance, the sum.

Summary statistics, such as the mean, median, maximum value or standard deviation, are other examples of aggregation functions.

In [54]:
np.sum(v)

71.425

In [55]:
np.mean(v), np.sum(v) / v.shape[0]

(14.285, 14.285)

In [56]:
np.median(v)

1.0

In [57]:
np.std(v), np.sqrt(np.mean(v**2 - np.mean(v)**2))

(29.520347220180188, 29.52034722018018)

In [58]:
np.max(v)

73.0

In [59]:
np.min(v)

-6.0

If the input is a matrix, these functions act on all the elements.

But you can also select a particular axis to act on.

For instance, to compute a vector that contains the sum of the columns:

In [60]:
np.sum(mat, axis=1)

array([  7.59, -16.61,  -6.23,  13.15,  22.  ])